version: '3.8'

services:
  email-service:
    build: .
    container_name: email-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=sancharaevents@gmail.com
      - SPRING_MAIL_PASSWORD=qmbo sgkn oilg myzd
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    depends_on:
      - smtp-server
    restart: always
  smtp-server:
    image: namshi/smtp
    container_name: smtp-server
    ports:
      - "1025:25"
