services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-management-service
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./target/EventManagmentSystem-0.0.1-SNAPSHOT.jar:/app/app.jar
