spring.data.mongodb.uri=mongodb+srv://sancharaevents:Jyk9aAMKO5wOnaH5@eventmanagementservice.npq3ba0.mongodb.net/EventManagementService?retryWrites=true&w=majority
cloudinary.cloud_name=dgiusuxyr
cloudinary.api_key=865993768466761
cloudinary.api_secret=VXJwxaVUu-9qGkqlscw55OulNaM
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html
spring.docker.compose.enabled=false





