spring.datasource.url=jdbc:postgresql://pg-2b59a7bc-library-mgmt-sys.e.aivencloud.com:18857/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_qoUZFzoDmLoS3BpmYat
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.transaction.jta.platform=enable

logging.level.root=INFO
server.port=8084
server.error.include-message=always
