# spring.application.name=demo

# Server Port Configuration
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/sanchaara_db
spring.datasource.username=user_sc
spring.datasource.password=u&#Ka1L3Ap01
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Java Persistence API) Configuration
spring.jpa.hibernate.ddl-auto=update 
# Automatically update schema. Use 'validate' or 'none' in production.
spring.jpa.show-sql=true 
# Show SQL queries in the console (good for development)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true 
# Format SQL queries in the console

# Logging
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO 
# Set to DEBUG to see more Hibernate logs

# API base path (optional)
# spring.data.rest.base-path=/api